<div id="origin-firstrun">
	<div id="fb-root"></div>
	<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=222225781217824";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

	<?php print get_avatar('greg@siteorigin.com', 44); ?>
	<a href="#" class="dismiss">dismiss</a>
	<strong>
		Hi! I'm Greg from SiteOrigin. I hope you enjoy <?php print $theme['Name'] ?>!
		If you need help, read its <a href="http://siteorigin.com/docs/<?php print strtolower($theme['Name']) ?>/" target="_blank">documentation</a>
		or <a href="mailto:support@siteorigin.com">contact me</a>.<br/>
		Please follow me on Facebook and Twitter for updates and new free themes :)
		<div class="social">
			<div class="follow twitter">
				<a href="https://twitter.com/siteorigin" class="twitter-follow-button" data-show-count="false" data-show-screen-name="false">Follow @siteorigin</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
			</div>

			<div class="follow facebook">
				<div class="fb-like" data-href="http://www.facebook.com/SiteOrigin" data-send="false" data-layout="button_count" data-width="120" data-show-faces="true"></div>
			</div>
		</div>
	</strong>
</div>