<?php if(file_exists(dirname(__FILE__).'/messages/'.$bar.'.html')) : ?>
	<div id="siteorigin-admin-bar" data-type="<?php print esc_attr($bar) ?>">
		<div class="inner">
			<img src="<?php print $icon ?>" class="icon" width="44" height="44" />
			<a href="#" class="dismiss">dismiss</a>
			
			<strong>
				<?php include(dirname(__FILE__).'/messages/'.$bar.'.html'); ?>
			</strong>
		</div>
	</div>
<?php endif ?>