<div class="pagination pagination-search">
	<ul>
		<?php if($paged - self::PAGINATION_SEARCH_SPREAD > 1) : ?>
			<li class="first pagination-button"><a href="<?php print OriginPaginationController::page_url(1) ?>">First</a></li>
		<?php endif; ?>
		
		<?php if($paged > 1) : ?>
			<li class="previous pagination-button"><a href="<?php print OriginPaginationController::page_url($paged-1 == 1 ? 1 : $paged - 1) ?>"><?php _e('Prev', 'siteorigin') ?></a></li>
		<?php endif ?>
		
		<?php if($paged - self::PAGINATION_SEARCH_SPREAD > 1) : ?>
			<li class="ellipsis"><span>&hellip;</span></li>
		<?php endif; ?>
		
		<?php for($i = max(1, $paged - self::PAGINATION_SEARCH_SPREAD); $i <= min($max_page, $paged + self::PAGINATION_SEARCH_SPREAD); $i++) : ?>
			<?php if($i == $paged) : ?>
				<li class="current"><span><?php print $i ?><span></li>
			<?php else : ?>
				<li class="page pagination-button"><a href="<?php print OriginPaginationController::page_url($i) ?>"><?php print $i ?></a></li>
			<?php endif; ?>
		<?php endfor; ?>

		<?php if($paged + self::PAGINATION_SEARCH_SPREAD < $max_page) : ?>
			<li class="ellipsis"><span>&hellip;</span></li>
		<?php endif; ?>
		
		<?php if($paged < $max_page) : ?>
			<li class="next pagination-button"><a href="<?php print OriginPaginationController::page_url($paged + 1) ?>"><?php _e('Next', 'siteorigin') ?></a></li>
		<?php endif ?>
		
		<?php if($paged + self::PAGINATION_SEARCH_SPREAD < $max_page) : ?>
			<li class="last pagination-button"><a href="<?php print OriginPaginationController::page_url($max_page) ?>">Last</a></li>
		<?php endif; ?>
	</ul>
</div> 